sudo: required
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
  include:
    - node_js: "0.10"
      env: TEST_GRAPHICSMAGICK=TRUE
    - node_js: "0.10"
      env: TEST_IMAGEMAGICK=TRUE

install:
  # Run our install script
  - test/install.sh

  # Output the im/gm version
  - if test -n "$TEST_IMAGEMAGICK"; then convert -version; else gm -version; fi

  # Install dependencies
  - npm install

notifications:
  email: false

